mapping_header_name:
  admin: Admin
  categories: Categories
  dashboard: Tableau de board
  albums: Albumes
  comments: Commentaires
  users: Utilisateurs
  contents: Contenus
  article: Article
  menus: Menus
  events: Événements
  settings: Paramètres
  roles: Rôles

# SIDEBAR ITEMS
sidebar_items:
  dashboard:
    name: Tableau de board
    slug:
      controller: Admin
      action: default


  content_add:
    name: Contenus
    slug:
      controller: Contents
      action: index

    dropdown:
      slugs:
        content_add:
          controller: Contents
          action: createContents
          label: Création du contenue

        page_view:
          controller: Contents
          action: listesPages
          label: Liste des pages

        article_view:
          controller: Contents
          action: listesArticles
          label: Liste des articles

  user_add:
    name: Utilisateurs
    slug:
      controller: Users
      action: listUsers

    dropdown:
      slugs:
        user_add:
          controller: Users
          action: createUsers
          label: Ajouter un utilisateur

  role_view:
    name: Rôles
    slug:
      controller: Admin
      action: roles

    dropdown:
      slugs:
        roles_add:
          controller: Admin
          action: roles
          label: Liste des rôles

        roles_list:
          controller: Admin
          action: rolesAdd
          label: Ajouter un rôle

  comment_perm:
    name: Commentaires
    slug:
      controller: Comments
      action: listNotConfirm

  categorie_view:
    name: Categories
    slug:
      controller: Categories
      action: index

    dropdown:
      slugs:
        album:
          controller: Categories
          action: album
          label: Albume

        article:
          controller: Categories
          action: article
          label: Article

        event:
          controller: Categories
          action: event
          label: Événement

  menus:
    name: Menus
    slug:
      controller: Admin
      action: menus

  event_add:
    name: Événements
    slug:
      controller: Events
      action: listEvents

    dropdown:
      slugs:
        event_add:
          controller: Events
          action: createEvents
          label: Création d'événement


  settings:
    name: Paramètres
    slug:
      controller: Settings
      action: config

    dropdown:
      slugs:
        config_settings:
          controller: Settings
          action: config
          label: Configuration

        template_settings:
          controller: Settings
          action: template
          label: Theme

        header_settings:
          controller: Settings
          action: header
          label: Header

        footer_settings:
          controller: Settings
          action: footer
          label: Footer