mapping_header_name:
  admin: Admin
  categories: Categories
  dashboard: Tableau de board
  albums: Albumes
  comments: Commentaires
  users: Utilisateurs
  contents: Contenus
  article: Article
  menus: Menus
  event: Événement

# SIDEBAR ITEMS
sidebar_items:
  dashboard:
    name: Tableau de board
    slug:
      controller: Admin
      action: default

  contents:
    name: Contenus
    slug:
      controller: Contents
      action: index

    dropdown:
      slugs:
        create_contents:
          controller: Contents
          action: createContents
          label: Création du contenue

        pages_lists:
          controller: Contents
          action: listesPages
          label: Liste des pages

        article_lists:
          controller: Contents
          action: listesArticles
          label: Liste des articles

  users:
    name: Utilisateurs
    slug:
      controller: Admin
      action: loadUser

  comments:
    name: Commentaires
    slug:
      controller: Comments
      action: listNotConfirm

  categories:
    name: Categories
    slug:
      controller: Categories
      action: index

    dropdown:
      slugs:
        album:
          controller: Categories
          action: album
          label: Albume

        article:
          controller: Categories
          action: article
          label: Article

        event:
          controller: Categories
          action: event
          label: Événement

  menus:
    name: Menus
    slug:
      controller: Admin
      action: menus

  event:
    name: Événement
    slug:
      controller: Admin
      action: menus

