"/":
  controller: Pages
  action: default

"/contenu":
  controller: Pages
  action: content

# USERS
"/liste_des_utilisateurs":
  controller: Users
  action: default

"/creation_de_compte":
  controller: Users
  action: register

"/mot_de_passe_oublie":
  controller: Users
  action: forgetPassword

"/connexion":
  controller: Users
  action: login

"/deconnexion":
  controller: Users
  action: logout
  needAuth: true

"/mon_compte":
  controller: Users
  action: dashboard
  needAuth: true

# ADMIN
"/admin/dashboard":
  controller: Admin
  action: default
  needGroups: admin

"/admin/users":
  controller: Admin
  action: loadUser
  needGroups: admin

"/admin/menus":
  controller: Admin
  action: menus
  needGroups: admin

"/admin/menus/edit":
  controller: Admin
  action: menusEdit
  needGroups: admin

"/admin/creation_du_contenu":
  controller: Contents
  action: createContents

"/admin/listes_de_pages":
  controller: Contents
  action: listesPages

"/admin/albums":
  controller: Admin
  action: loadAlbum

"/admin/categories":
  controller: Categories
  action: index

"/admin/categories/article":
  controller: Categories
  action: article

"/admin/categories/album":
  controller: Categories
  action: album

"/admin/categories/delete":
  controller: Categories
  action: delete

"/admin/categories/update":
  controller: Categories
  action: index
