"/":
  controller: Pages
  action: default

"/creation_de_compte":
  controller: Users
  action: register

"/mot_de_passe_oublie":
  controller: Users
  action: forgetPassword

"/connexion":
  controller: Users
  action: login

"/liste_des_utilisateurs":
  controller: Users
  action: default

"/contenu":
  controller: Pages
  action: content
"/admin":
  controller: Admin
  action: default

"/admin/users":
  controller: Admin
  action: loadUser

"/authentication":
  controller: Admin
  action: loadAuth

"/admin/pages":
  controller: Pages
  action: index

"/admin/album":
  controller: Admin
  action: loadAlbum

"/admin/categories":
  controller: Categories
  action: index

"/admin/categories/delete":
  controller: Categories
  action: delete

"/admin/categories/update":
  controller: Categories
  action: index