"/":
  controller: Pages
  action: default

"/creation_de_compte":
  controller: Users
  action: register

"/mot_de_passe_oublie":
  controller: Users
  action: forgetPassword

"/connexion":
  controller: Users
  action: login

"/liste_des_utilisateurs":
  controller: Users
  action: default

"/contenu":
  controller: Pages
  action: content