"/":
  controller: Pages
  action: default

"/contenu":
  controller: Pages
  action: content

# USERS
"/liste_des_utilisateurs":
  controller: Users
  action: default

"/creation_de_compte":
  controller: Users
  action: register

"/mot_de_passe_oublie":
  controller: Users
  action: forgetPassword

"/connexion":
  controller: Users
  action: login

"/deconnexion":
  controller: Users
  action: logout
  needAuth: true

"/mon_compte":
  controller: Users
  action: dashboard
  needAuth: true

# ADMIN
"/admin":
  controller: Admin
  action: default
  needGroups: admin

"/admin/users":
  controller: Admin
  action: loadUser
  needGroups: admin

"/admin/menus":
  controller: Admin
  action: menus
  needGroups: admin

"/admin/menus/edit":
  controller: Admin
  action: menusEdit
  needGroups: admin
